In [1]:
#텐서 기본
import torch
X = torch.Tensor(2,4)#2X3크기의 텐서 생성, 원소는 임의의 난수
X

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [2]:
X = torch.tensor([[1,2,3],[4,5,6]])#원하는 값 직접입력 가능
print(X)
print(X.dtype)#텐서에 저장된 원소의 자료형
print(X.data)#print(X)와 같음
print(X.device)#어떤기기에 텐서를 올리는지
print(X.requires_grad)#텐서에 대한 기울기를 저장할 것인지, default는 False

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.int64
tensor([[1, 2, 3],
        [4, 5, 6]])
cpu
False


In [3]:
x_tensor = torch.tensor(data=[2.0, 3.0], requires_grad=True)
print(x_tensor.dtype)

torch.float32


In [4]:
#torch.tensor는 dtype dafault가 int여서 float형으로 자료형을 변환해야 함. torch.Tensor는 float32
x = torch.tensor(data=[2,3], dtype=torch.float32, requires_grad=True) 
y = x**2
z = 2*y +3

target = torch.tensor([3,4])
loss = torch.sum(torch.abs(z-target))
loss.backward()#연산 그래프를 따라가면서 기울기 계산

print(x.grad, y.grad, z.grad)

tensor([ 8., 12.]) None None


c:\users\user\anaconda3\envs\pytorch\lib\site-packages\ipykernel_launcher.py:10: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information.
  # Remove the CWD from sys.path while we load stuff.


In [5]:
import torch
import torch.nn as nn#다양한 신경망 layer, model 포함
import torch.optim as optim#경사하강법 알고리즘
import torch.nn.init as init#텐서의 초기값을 주기위해 필요한 함수

In [ ]:
num_data = 1000
num_epoch = 10000

noise = init.normal_(torch.Tensor(num_data,1), std=1)
x = init.uniform_(torch.Tensor(num_data, 1), -15, 15)
y = (x**2)+3#비선형으로 한번 꼬아서
y_noise = y+ noise

model = nn.Sequential(
        nn.Linear(1,6),
        nn.ReLU(),
        nn.Linear(6,10),
        nn.ReLU(),
        nn.Linear(10,6),
        nn.ReLU(),
        nn.Linear(6,1))#4-layer fully-connected-layer

loss_fn = nn.L1Loss()
optimizer = optim.Adam(model.parameters(), lr=0.0002)

loss_array = []
for i in range(num_epoch):
    optimizer.zero_grad()
    output = model(x)
    
    loss = loss_fn(output,y_noise)
    loss.backward()
    optimizer.step()
    loss_array.append(loss.data)#loss값만 필요하니까 loss.data사용
    
    if (i%100)==0:
        print(f'epoch{i} loss:{loss.data}')


epoch0 loss:74.72109985351562
