In [1]:
#텐서 기본
import torch
X = torch.Tensor(2,4)#2X3크기의 텐서 생성, 원소는 임의의 난수
X

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [2]:
X = torch.tensor([[1,2,3],[4,5,6]])#원하는 값 직접입력 가능
print(X)
print(X.dtype)#텐서에 저장된 원소의 자료형
print(X.data)#print(X)와 같음
print(X.device)#어떤기기에 텐서를 올리는지
print(X.requires_grad)#텐서에 대한 기울기를 저장할 것인지, default는 False

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.int64
tensor([[1, 2, 3],
        [4, 5, 6]])
cpu
False


In [3]:
x_tensor = torch.tensor(data=[2.0, 3.0], requires_grad=True)
print(x_tensor.dtype)

torch.float32


In [4]:
#torch.tensor는 dtype dafault가 int여서 float형으로 자료형을 변환해야 함. torch.Tensor는 float32
x = torch.tensor(data=[2,3], dtype=torch.float32, requires_grad=True) 
y = x**2
z = 2*y +3

target = torch.tensor([3,4])
loss = torch.sum(torch.abs(z-target))
loss.backward()#연산 그래프를 따라가면서 기울기 계산

print(x.grad, y.grad, z.grad)

tensor([ 8., 12.]) None None


c:\users\user\anaconda3\envs\pytorch\lib\site-packages\ipykernel_launcher.py:10: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information.
  # Remove the CWD from sys.path while we load stuff.


In [5]:
import torch
import torch.nn as nn#다양한 신경망 layer, model 포함
import torch.optim as optim#경사하강법 알고리즘
import torch.nn.init as init#텐서의 초기값을 주기위해 필요한 함수

In [7]:
num_data = 1000
num_epoch = 10000

noise = init.normal_(torch.Tensor(num_data,1), std=1)
x = init.uniform_(torch.Tensor(num_data, 1), -15, 15)
y = (x**2)+3#비선형으로 한번 꼬아서
y_noise = y+ noise

model = nn.Sequential(
        nn.Linear(1,6),
        nn.ReLU(),
        nn.Linear(6,10),
        nn.ReLU(),
        nn.Linear(10,6),
        nn.ReLU(),
        nn.Linear(6,1))#4-layer fully-connected-layer

loss_fn = nn.L1Loss()
optimizer = optim.Adam(model.parameters(), lr=0.0002)

loss_array = []
for i in range(num_epoch):
    optimizer.zero_grad()
    output = model(x)
    
    loss = loss_fn(output,y_noise)
    loss.backward()
    optimizer.step()
    loss_array.append(loss.data)#loss값만 필요하니까 loss.data사용
    
    if (i%100)==0:
        print(f'epoch{i} loss:{loss.data}')


epoch0 loss:81.0762939453125
epoch100 loss:80.83755493164062
epoch200 loss:80.74433135986328
epoch300 loss:80.53543853759766
epoch400 loss:80.17977142333984
epoch500 loss:79.67991638183594
epoch600 loss:78.97834014892578
epoch700 loss:78.0007095336914
epoch800 loss:76.61815643310547
epoch900 loss:74.72564697265625
epoch1000 loss:72.22037506103516
epoch1100 loss:68.99864959716797
epoch1200 loss:64.99720001220703
epoch1300 loss:60.305118560791016
epoch1400 loss:55.09256362915039
epoch1500 loss:49.555686950683594
epoch1600 loss:43.94168472290039
epoch1700 loss:38.53467559814453
epoch1800 loss:33.77058410644531
epoch1900 loss:30.127965927124023
epoch2000 loss:27.395465850830078
epoch2100 loss:25.48948097229004
epoch2200 loss:24.29296112060547
epoch2300 loss:23.52316665649414
epoch2400 loss:23.081315994262695
epoch2500 loss:22.747385025024414
epoch2600 loss:22.47711753845215
epoch2700 loss:22.252132415771484
epoch2800 loss:22.027496337890625
epoch2900 loss:21.76015281677246
epoch3000 loss:2